table 'TopN Foreign Port'
	lineageTag: 65e74bb6-ff39-461c-9a5e-5b855ab2144d

	measure 'Foreign_Port Rank by' =
			
			IF(SELECTEDVALUE(Data[Value4]) = "STD Quantity",RANKX(ALL(IndiaImport[PORT_OF_SHIPMENT]), [Total Quantity] , , DESC,Dense), IF(SELECTEDVALUE(Data[Value4]) = "Records", RANKX(ALL(IndiaImport[PORT_OF_SHIPMENT]), [Count of records] , , DESC,Dense),  IF(SELECTEDVALUE(Data[Value4]) = "Duty Paid", RANKX(ALL(IndiaImport[PORT_OF_SHIPMENT]), [Total Duty Paid] , , DESC,Dense), RANKX(ALL(IndiaImport[PORT_OF_SHIPMENT]), [Total Value] , , DESC,Dense) )))
		formatString: 0
		lineageTag: 1a4022d8-cf55-41a1-93b3-fbaaeb49bd1a

	measure 'TOPN Foreign_Port_Rank' =
			
			IF('TopN Foreign Port'[Foreign_Port Rank by]<=SELECTEDVALUE('TopN Foreign Port'[Value]),1,0)
		formatString: 0
		lineageTag: c85b89c3-5f3b-4854-b7bc-e820a64d58ee

	measure 'Title Foreign_Ports' = Selectedvalue('TopN Foreign Port'[Metric]) & " Foreign Ports by " & SELECTEDVALUE(Data[Value4])
		lineageTag: 3879377f-de50-4b1b-b6c0-0f662df99607

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 5bc890b5-7e38-4975-84a4-6b1f63a62624
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 51714535-171c-43f7-ba67-c5bdb0fb7e86
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition 'TopN Foreign Port' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lEK8Q9QADJidYB8UxjfFMw3gskDGbGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

