table 'All Measures'
	lineageTag: ed904d4b-c656-4274-b2be-c5d012b71a3e

	measure 'Top importers by quantity' =
			
			Var topRank = RANKX(ALL('Armenia Import'[IMPORTER_NAME]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Origin_Country Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 0ca502e2-853f-423c-992e-b24adea309b4

	measure 'Total Quantity' = SUM('Armenia Import'[QUANTITY])
		formatString: 0.00
		lineageTag: 9499200f-4faf-4d66-bf0d-2b6620958a66

	measure 'Total Value' = SUM('Armenia Import'[TOTAL_VALUE])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: dc156b6f-f08d-4f12-be3b-1c26d72f7392

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Top importers by value' =
			
			Var topRank = RANKX(ALL('Armenia Import'[IMPORTER_NAME]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Origin_Country Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 4af5b2ef-a4c1-40fb-9d1b-08a524ee6f99

	measure 'Total Records' = ```
			DISTINCTCOUNT('Armenia Import'[RECORD_ID]) 
			```
		formatString: 0
		lineageTag: e1c3ef15-5b02-41ee-aae8-1746c8c7cb17

	measure 'Top importers by records' =
			
			Var topRank = RANKX(ALL('Armenia Import'[IMPORTER_NAME]), [Total Records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Origin_Country Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 7c8f62e1-c9f3-488b-995b-917c720ea67c

	measure 'Total Duty Paid' = SUM('Brazil Import'[TOTAL_TAX])
		lineageTag: e7a6d06a-b802-4559-97fe-2e27ad24b977

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top importers by duty paid' =
			
			Var topRank = RANKX(ALL('Armenia Import'[IMPORTER_NAME]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Origin_Country Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 66573da4-ac31-43a3-9d8f-46eab177de55

	measure 'Top supplier by quantity' =
			
			Var topRank = RANKX(ALL('Brazil Import'[SUPPLIER_NAME]), [Total Quantity],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Supplier_Name Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 380128cd-883e-4917-b089-27b50ead4c19

	measure 'Top supplier by value' =
			
			Var topRank = RANKX(ALL('Brazil Import'[SUPPLIER_NAME]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Supplier_Name Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 56f6e13b-9ec6-4d0a-b7e7-0e115ba02728

	measure 'Top supplier by records' =
			
			Var topRank = RANKX(ALL('Brazil Import'[SUPPLIER_NAME]), [Total Records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Supplier_Name Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: fabd11d8-4d83-4483-8aa9-4f44e81fd58e

	measure 'Top supplier by duty paid' =
			
			Var topRank = RANKX(ALL('Brazil Import'[SUPPLIER_NAME]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Supplier_Name Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 31dbf723-41d6-4c73-aedd-79b561cd3e71

	measure 'Top Countries by value' =
			
			Var topRank = RANKX(ALL('Brazil Import'[ORIGIN_COUNTRY]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Title Importer], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: b1a20e8c-3f80-4762-995b-69d173927fc7

	measure 'Top Countries by records' =
			
			Var topRank = RANKX(ALL('Brazil Import'[ORIGIN_COUNTRY]), [Total Records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Title Importer], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 6f2280ca-8a5a-4253-8264-b6de8494f3f6

	measure 'Top Countries by quantity' =
			
			Var topRank = RANKX(ALL('Brazil Import'[ORIGIN_COUNTRY]), [Total Quantity],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Title Importer], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 45c4b480-2dcd-4f8a-a349-819b1cba76fd

	measure 'Top Countries by duty paid' =
			
			Var topRank = RANKX(ALL('Brazil Import'[ORIGIN_COUNTRY]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Title Importer], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: a0ea575d-3164-41cd-a59a-dbc51e2f3500

	measure 'Top indian port by records' =
			
			Var topRank = RANKX(ALL('IndiaImport'[INDIAN_PORT]), [Count of records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Indian_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 16f0a680-6c31-4e58-9c17-70e66bfc7d39

	measure 'Top indian port by quantity' =
			
			Var topRank = RANKX(ALL('IndiaImport'[INDIAN_PORT]), [Total Quantity],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Indian_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: d08f8929-ec37-4a7f-8d5e-d4d87fc096e8

	measure 'Top indian port by value' =
			
			Var topRank = RANKX(ALL('IndiaImport'[INDIAN_PORT]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Indian_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 1dde51e9-06d7-4451-b5bf-d4c63329386b

	measure 'Top indian port by duty paid' =
			
			Var topRank = RANKX(ALL('IndiaImport'[INDIAN_PORT]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Indian_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 3358ed59-b8cd-4127-8ec8-49fa32e5223f

	measure 'Top HS CODE by duty paid' =
			
			Var topRank = RANKX(ALL('Armenia Import'[HS_CODE]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [HS_Code Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 75b05b86-c796-42d3-a03e-2954964e8216

	measure 'Top HS CODE by quantity' =
			
			Var topRank = RANKX(ALL('Armenia Import'[HS_CODE]), [Total Quantity],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [HS_Code Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: a54504f3-50f8-43c8-9446-be0e87bd3da2

	measure 'Top HS CODE by value' =
			
			Var topRank = RANKX(ALL('Armenia Import'[HS_CODE]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [HS_Code Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: b2ab42c7-588b-44a4-ba89-7b9b2c5ba346

	measure 'Top HS CODE by Records' =
			
			Var topRank = RANKX(ALL('Armenia Import'[HS_CODE]), [Total Records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [HS_Code Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 96da5d69-357d-4a38-9a00-a0270c193937

	measure 'Top Foriegn Port by duty paid' =
			
			Var topRank = RANKX(ALL('IndiaImport'[PORT_OF_SHIPMENT]), [Total Duty Paid],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Foreign_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: b23a86c3-7aff-473d-b0df-03a5b3ca9ab2

	measure 'Top Foriegn Port by Value' =
			
			Var topRank = RANKX(ALL('IndiaImport'[PORT_OF_SHIPMENT]), [Total Value],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Foreign_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 36e8aa2d-0252-48b8-8d7a-f446fe3292b8

	measure 'Top Foriegn Port by quantity' =
			
			Var topRank = RANKX(ALL('IndiaImport'[PORT_OF_SHIPMENT]), [Total Quantity],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Foreign_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 3640647d-4db9-468c-94bd-07f220ae05c1

	measure 'Top Foriegn Port by records' =
			
			Var topRank = RANKX(ALL('IndiaImport'[PORT_OF_SHIPMENT]), [Count of records],,DESC)
			Var result = SWITCH(
			    TRUE(),
			    topRank <= [Foreign_Port Rank by], 1, BLANK())
			return
			 result
		formatString: 0
		lineageTag: 2f1fe0f0-b38e-4ff6-bd96-069262cc48f2

	measure IsFiltered = ISFILTERED('Armenia Import'[IMPORTER_NAME_EN]) || ISFILTERED('Armenia Import'[SUPPLIER_NAME_EN]) || ISFILTERED('Armenia Import'[ORIGIN_COUNTRY]) || ISFILTERED('Armenia Import'[HS_CODE]) || ISFILTERED('Armenia Import'[EXPORT_COUNTRY])
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16fa4e9d-6670-4262-ae9e-edb63aadfe7e

	measure Message = if([IsFiltered],"", " Select the Fields")
		lineageTag: 7e2f2469-f230-4663-86dc-d660f2ab3d2b

	measure 'Hide Visual' = If([IsFiltered], 1,0)
		formatString: 0
		lineageTag: 7a862c03-b271-4f62-b404-c54373b25822

	measure Transparent = if([IsFiltered],"#FFFFFF00", "White")
		lineageTag: 07866f6a-6aef-4d68-bfff-6d2db3ef44ad

	measure 'Make Transparent' = ```
			
			      IF(not
			         [IsFiltered],
			         "#FFFFFF00", -- returns transparent if Check Filtered is True
			         "#005D91"
			      )
			```
		lineageTag: 58003651-a5a7-425b-8943-7be6c6d6bf5d

	measure BlankDatameasure = BLANK()
		formatString: 0
		lineageTag: 780eb0b1-9b27-4154-bd0c-e39b021feda5

	measure 'Sum Total Value' = if(( not SELECTEDVALUE('Brazil Import'[IMPORTER_NAME]) = BLANK()), SUM('Brazil Import'[UNIT_VALUE_USD]), BLANK())
		lineageTag: 05ca05be-8c25-4dd6-9942-5d135e6142c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Make text Transparent' = ```
			
			      IF(not
			         [IsFiltered],
			         "", -- returns transparent if Check Filtered is True
			         "GO"
			      )
			```
		lineageTag: c8ea8395-1415-4215-8b85-0b12c4a29b4e

	measure 'Hex Code_USD' = COUNT('All Measures'[TOPN Value])
		formatString: 0
		lineageTag: e3849474-8e64-406e-b1fd-f9a690487602

	measure 'Total Shipments' = DISTINCTCOUNT('Armenia Import'[RECORDS_TAG])
		formatString: 0
		lineageTag: 155a8c22-8cf7-440e-aacf-83ee0b615f6a

	measure 'Total Suppliers' = DISTINCTCOUNT('Armenia Import'[SUPPLIER_NAME_EN])
		formatString: 0
		lineageTag: f631eeee-95bf-41f2-a3d4-155201ecc93a

	measure 'Total Importers' = DISTINCTCOUNT('Armenia Import'[IMPORTER_NAME_EN])
		formatString: 0
		lineageTag: e68fbc81-ccc1-4316-8345-0c9b936de914

	measure 'Total HS_Code' = DISTINCTCOUNT('Armenia Import'[HS_CODE])
		formatString: 0
		lineageTag: 246f27b5-6f88-4203-a9a3-4f21a54bf41b

	measure 'Avg Unit Price USD' = AVERAGE('Brazil Import'[UNIT_VALUE_USD])
		lineageTag: 26904983-4425-4b3f-8858-3b4e9072d6d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Weights' = SUM('Armenia Import'[WEIGHT_KG])
		lineageTag: 06d9d702-4576-4799-9af9-a2aefc04f4ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TOPN Value'
		formatString: 0
		lineageTag: a4a5189f-938c-4ff1-adcb-358572407b0a
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TOPN Value]

		annotation SummarizationSetBy = Automatic

	partition 'All Measures' = calculated
		mode: import
		source = Row("TOPN Value", BLANK())

	annotation PBI_Id = a55b0ea4c1f04ddaa7406902a2cc7340

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

