table 'TOP 50 HS_Code'
	lineageTag: 8b74d4e7-3853-49a7-9898-c0a5ff055bc6

	measure 'HS_Code Rank by Value' = ```
			
			IF(SELECTEDVALUE(Data[Value4]) = "Quantity",RANKX(ALL('Armenia Export'[HS_CODE]), [Total Quantity] , , DESC,Dense), 
			IF(SELECTEDVALUE(Data[Value4]) = "Records", RANKX(ALL('Armenia Export'[HS_CODE]), [Total Records] , , DESC,Dense), 
			RANKX(ALL('Armenia Export'[HS_CODE]), [Total Value] , , DESC,Dense) ))
			```
		formatString: 0
		lineageTag: 692f1675-3fa2-4693-a053-c31421360a6d

	measure 'TOP50 HS_Code Rank' =
			
			IF('TOP 50 HS_Code'[HS_Code Rank by Value]<=SELECTEDVALUE('TOP 50 HS_Code'[Value]),1,0)
		formatString: 0
		lineageTag: ce2c9baf-e7fb-47e7-8f65-3ca589f11141

	measure Title_HS_Code = Selectedvalue('TOP 50 HS_Code'[Metric]) & " HS_Code by " & SELECTEDVALUE(Data[Value4])
		lineageTag: a63b102d-3ded-4a76-8bb0-44afb9a09d92

	measure HS_CodeRank =
			
			VAR selectedvalue= SELECTEDVALUE('TOP 50 HS_Code'[Value])
			RETURN
			IF('TOP 50 HS_Code'[HS_Code Rank by Value]<=SELECTEDVALUE('TOP 50 HS_Code'[Value]),1,0)
		formatString: 0
		lineageTag: 4e15674a-105e-4c0a-a8b7-dce1973af73c

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 03ebef8c-2b9e-419d-9f9d-21b34279dd60
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 5826efd1-da5c-4d6a-808a-ff10e752c7d1
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition 'TOP 50 HS_Code' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjJQ0lEK8Q9QADJidaKVjGF8YwjfBMY3gfBNYXwgIzYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

