table 'TOP 50 Destination Country'
	lineageTag: d4e6a78e-988f-42c6-8f7b-e3b73b3f7b77

	measure 'Destination Country Rank by Value' = ```
			
			IF(SELECTEDVALUE(Data[Value4]) = "Quantity",RANKX(ALL('Armenia Export'[DESTINATION_COUNTRY]), [Total Quantity] , , DESC,Dense), 
			IF(SELECTEDVALUE(Data[Value4]) = "Records", RANKX(ALL('Armenia Export'[DESTINATION_COUNTRY]), [Total Records] , , DESC,Dense), 
			RANKX(ALL('Armenia Export'[DESTINATION_COUNTRY]), [Total Value] , , DESC,Dense) ))
			```
		formatString: 0
		lineageTag: 79819f40-87a1-46d9-a5bf-05916a36bb36

	measure 'TOP50 Destination Country Rank' =
			
			IF('TOP 50 Destination Country'[Destination Country Rank by Value]<=SELECTEDVALUE('TOP 50 Destination Country'[Value]),1,0)
		formatString: 0
		lineageTag: dddc9205-124f-4113-b500-ee027b59a66a

	measure Title_Destination_Country = Selectedvalue('TOP 50 Destination Country'[Metric]) & " Destination Countries by " & SELECTEDVALUE(Data[Value4])
		lineageTag: b8dda95d-d97d-47cd-a79a-524254f8e173

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 7b7afa4f-6dab-445a-b3a4-9fafd45e8bcf
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 197786ef-f04b-4de1-aaea-8641239695ef
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition 'TOP 50 Destination Country' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjJQ0lEK8Q9QADJidaKVjGF8YwjfBMY3gfBNYXwgIzYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

