table 'TOPN HS Codes'
	lineageTag: 8c2ff23a-3de1-4b4f-b0c1-b16e1d040063

	measure 'Title HS_Code' = Selectedvalue('TOPN HS Codes'[Metric]) & " HS_Code by " & SELECTEDVALUE(Data[Value4])
		lineageTag: 39bb355b-4dd5-4e69-85a1-d2ada86130e2

	measure 'HS_Code_Name Rank by' = ```
			
			IF(SELECTEDVALUE(Data[Value4]) = "Quantity",RANKX(ALL('Armenia Export'[HS_CODE]), [Total Quantity] , , DESC,Dense), 
			IF(SELECTEDVALUE(Data[Value4]) = "Records", RANKX(ALL('Armenia Export'[HS_CODE]), [Total Records] , , DESC,Dense), 
			RANKX(ALL('Armenia Export'[HS_CODE]), [Total Value] , , DESC,Dense) ))
			```
		formatString: 0
		lineageTag: 678e78db-c877-47f9-ad14-4884988340fe

	measure 'TOPN HS_Code_Rank' =
			
			IF('TOPN HS Codes'[HS_Code_Name Rank by]<=SELECTEDVALUE('TOPN HS Codes'[Value]),1,0)
		formatString: 0
		lineageTag: f2530669-aa0a-4c93-bcc1-1e87561a48c8

	column Value
		dataType: int64
		formatString: 0
		lineageTag: f4a6603d-6311-4765-973d-585abaa44bcd
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: c4675333-67fb-40a7-9358-650d33c90935
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition 'TOPN HS Codes' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lEK8Q9QADJidYB8UxjfFMw3gskDGbGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

