table 'Theme Mode'
	lineageTag: d83258c9-877f-4e96-8fa9-4fc8420a650c

	column Mode
		dataType: string
		lineageTag: 963c62c4-8ab6-4409-a860-1d45fccd7c66
		summarizeBy: none
		sourceColumn: Mode

		annotation SummarizationSetBy = Automatic

	column BG
		dataType: string
		lineageTag: 79040c00-99a7-4b93-b612-edec01748809
		summarizeBy: none
		sourceColumn: BG

		annotation SummarizationSetBy = Automatic

	column 'Visual BG'
		dataType: string
		lineageTag: 99123153-4af7-483f-892d-ba80de939978
		summarizeBy: none
		sourceColumn: Visual BG

		annotation SummarizationSetBy = Automatic

	column Text
		dataType: string
		lineageTag: 64cb1dee-aa43-4074-ae95-830a67091bb1
		summarizeBy: none
		sourceColumn: Text

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 3ec688b4-0846-414c-91e6-8404ab848f1c
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition 'Theme Mode' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8slMzyhR0lFSdjVytXB1BLHcwADEMjI1MjEyBrHMDExdTZ2VYnWilVwSi7JBQoauRmbGRmBlFkZuxs6oWl3dQFApNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Mode = _t, BG = _t, #"Visual BG" = _t, Text = _t, Label = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Mode", type text}, {"BG", type text}, {"Visual BG", type text}, {"Text", type text}, {"Label", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

