table 'Theme Mode'
	lineageTag: b2a3fd86-3147-4c91-a1b4-18b7ba7ee07b

	column Mode
		dataType: string
		lineageTag: 8d65e5e1-1429-4b7b-ae90-c42b17bab258
		summarizeBy: none
		sourceColumn: Mode

		annotation SummarizationSetBy = Automatic

	column BG
		dataType: string
		lineageTag: e4b5227a-b3ec-40c7-bc8d-f22a5af93af9
		summarizeBy: none
		sourceColumn: BG

		annotation SummarizationSetBy = Automatic

	column 'Visual BG'
		dataType: string
		lineageTag: e5563d74-b7e2-4b66-8a2e-c0968ff985fc
		summarizeBy: none
		sourceColumn: Visual BG

		annotation SummarizationSetBy = Automatic

	column Text
		dataType: string
		lineageTag: cf045546-2062-452f-b754-c3554d813fe9
		summarizeBy: none
		sourceColumn: Text

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 893aa848-68c7-4cd8-aae3-925710a0261e
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition 'Theme Mode' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W+jC/Z56CT2Z6RomSjpKyq5GrhasjiOUGBiCWkamRiZExiGVmYOpq6qwUqwPWNlvBJbEoGyRu6GpkZmwEVmth5GbsjKrf1Q0ElWJjAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Mode = _t, BG = _t, #"Visual BG" = _t, Text = _t, Label = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Mode", type text}, {"BG", type text}, {"Visual BG", type text}, {"Text", type text}, {"Label", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

