table 'Food AOV Last 7 Days Line'
	lineageTag: 4b7e7f65-8c52-47fc-85b7-42838eee0d22

	column COUNT_id
		dataType: double
		sourceProviderType: double
		lineageTag: c2059ffe-13bc-4779-851c-ab666d8d9645
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: f378be07-abd3-44ab-8d25-85b79b216cd4
		summarizeBy: none
		sourceColumn: created_on_ist

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 5832721c-cfa4-4700-a7c4-6a3a5e50d90a
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5d303bcf-0923-4d16-adb8-48a27d70f57a
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: dcdccf62-6afa-4019-b3b5-c52906507289
		summarizeBy: none
		sourceColumn: Week
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food AOV Last 7 Days Line' = m
		mode: directQuery
		queryGroup: 'Food\Food- Last 7 Days\Food- Sales\Food-AOV'
		source = ```
				let 
				// Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    // // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				    // Reference all dynamic parameters
				    CityParam = if Value.Is(City_Parameter, type list) then City_Parameter else {City_Parameter},
				    AreaParam = if Value.Is(Area_Parameter, type list) then Area_Parameter else {Area_Parameter},
				    BUParam = if Value.Is(BusinessUnit_Parameter, type list) then BusinessUnit_Parameter else {BusinessUnit_Parameter},
				    BCParam = if Value.Is(BusinessClassifier_Parameter, type list) then BusinessClassifier_Parameter else {BusinessClassifier_Parameter},
				    TimeSlotParam = if Value.Is(TimeSlot_Parameter, type list) then TimeSlot_Parameter else {TimeSlot_Parameter},
				
				    // Build Dynamic Conditions
				    CityCondition = if List.NonNullCount(CityParam) > 0 then " | where city in (" & Text.Combine(List.Transform(CityParam, each "'" & _ & "'"), ", ") & ")" else "",
				    AreaCondition = if List.NonNullCount(AreaParam) > 0 then " | where area in (" & Text.Combine(List.Transform(AreaParam, each "'" & _ & "'"), ", ") & ")" else "",
				    BUCondition = if List.NonNullCount(BUParam) > 0 then " | where business_unit in (" & Text.Combine(List.Transform(BUParam, each "'" & _ & "'"), ", ") & ")" else "",
				    BCCondition = if List.NonNullCount(BCParam) > 0 then " | where business_classifier in (" & Text.Combine(List.Transform(BCParam, each "'" & _ & "'"), ", ") & ")" else "",
				    TimeSlotCondition = if List.NonNullCount(TimeSlotParam) > 0 then " | where time_slot in (" & Text.Combine(List.Transform(TimeSlotParam, each "'" & _ & "'"), ", ") & ")" else "",
				
				
				    // Combine All Filters
				    CombinedFilters = CityCondition & AreaCondition & BUCondition & BCCondition & TimeSlotCondition,
				
				    // Format the query with dynamic start and end times for yesterday in IST
				    Query = "let currentUser = current_principal_details()['UserPrincipalName'];
				    let userCities = toscalar(
				        Anobis_RLS_MV
				        | where UserEmail_ID == currentUser
				        | summarize make_list(city)
				    );
				    let hasAllAccess = toscalar(
				        Anobis_RLS_MV
				        | where UserEmail_ID == currentUser and city == 'cities'
				        | count
				    );
				    let currentweek = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLast7DaysFormatted & "') 
				    | where created_on_ist < datetime('"& EndofCurrentDateFormatted &"')
				            " & CombinedFilters & "
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION' 
				          and ((hasAllAccess > 0) or (city in (userCities)))
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend time_period='Daily Trend'
				    | project COUNT_id, created_on_ist, time_period;
				    let last_week = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLastWeekFormatted & "')
				    | where created_on_ist < datetime('"& EndofLastWeekFormatted &"')
				            " & CombinedFilters & " 
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION'
				          and ((hasAllAccess > 0) or (city in (userCities)))
				    | extend created_on_ist = datetime_add('hour', 168, created_on_ist) 
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend time_period='1 Week Ago'
				    | project COUNT_id, created_on_ist, time_period;
				    currentweek
				    | union last_week",
				
				        // // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Inserted Day of Week" = Table.AddColumn(Source, "Day of Week", each Date.DayOfWeek([created_on_ist]), Int64.Type),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Day of Week", "Week", each if [Day of Week] = 1 then "Mon" else if [Day of Week] = 2 then "Tue" else if [Day of Week] = 3 then "Wed" else if [Day of Week] = 4 then "Thur" else if [Day of Week] = 5 then "Fri" else if [Day of Week] = 6 then "Sat" else if [Day of Week] = 0 then "Sun" else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"created_on_ist", type datetime}, {"Week", type text}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

