table 'IM Cancelled Decompotion Tree- Last 7 Days'
	lineageTag: 4e48cabc-a5ea-46ac-9d16-1a06e9582e5d

	column City
		dataType: string
		lineageTag: a4f9f694-96cd-4243-988a-119b3d4f0255
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2504a6f5-343e-43b5-89b4-ea6fd81b1d0a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: f5360070-07dd-40f5-845c-99d001483a2d
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: string
		lineageTag: 5148719c-0184-4b7c-be57-0002385aa806
		summarizeBy: none
		sourceColumn: Store ID

		annotation SummarizationSetBy = Automatic

	column 'Delivery Type'
		dataType: string
		lineageTag: 21deab2b-e40d-4c81-abee-05099a5592e6
		summarizeBy: none
		sourceColumn: Delivery Type

		annotation SummarizationSetBy = Automatic

	column count_
		dataType: int64
		formatString: 0
		lineageTag: 91e9ff4a-30e8-4c0f-949b-031446928364
		summarizeBy: sum
		sourceColumn: count_

		annotation SummarizationSetBy = Automatic

	column 'Delivery Slot'
		dataType: string
		lineageTag: 4221915d-e79e-4cfd-bdc4-f8cd6fbe61eb
		summarizeBy: none
		sourceColumn: Delivery Slot

		annotation SummarizationSetBy = Automatic

	partition 'IM Cancelled Decompotion Tree- Last 7 Days' = m
		mode: import
		queryGroup: 'IM\IM-Last 7 Days\IM-Cancellation\IM-Cancelled Orders'
		source = ```
				let
				 // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 7 days ago in IST
				    Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				    // Set the start of the last 7 days to 12:00 AM IST
				    StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				    StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    EndofLast7Days = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofLast7DayFormatted = DateTime.ToText(EndofLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    
				    // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // Format the query with dynamic start and end times
				    Query = TableName & " 
				    | where created_at_ist >= datetime('" & StartOfLast7DaysFormatted & "')
				    | where  created_at_ist < datetime(' " & EndofLast7DayFormatted & " ')
				    | where dp_order_type == 'INSTAMART' and status == 'CANCELLED' and (order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level))
				    | summarize count() by city, region, zone, store_id, delivery_slot, delivery_type",
				
				    Source = AzureDataExplorer.Contents(Cluster, DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"city", "City"}, {"region", "Region"}, {"zone", "Zone"}, {"store_id", "Store ID"}, {"delivery_type", "Delivery Type"}, {"delivery_slot", "Delivery Slot"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

