table 'IM SDC%- Last 7 Days Line'
	lineageTag: 39f6bc61-c552-4f9b-a996-a7a64195430e

	column Time
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: a561e460-93ad-48a2-ae46-0a7e83f3c4cf
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column SDC%
		dataType: double
		sourceProviderType: double
		lineageTag: f1e99008-4e57-47b8-8b4e-1748e6a69324
		summarizeBy: sum
		sourceColumn: SDC%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 3c128872-dfcd-4f3f-83ef-235e415f055e
		summarizeBy: none
		sourceColumn: Time_period

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 50191c90-c1d3-454b-9d3a-a552911978ba
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: d617d6d2-eaa8-4b3a-93bf-88453fdc85a9
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	partition 'IM SDC%- Last 7 Days Line' = m
		mode: directQuery
		queryGroup: 'IM\IM-Last 7 Days\IM-Cancellation\IM-SDC'
		source = ```
				let
				   // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 7 days ago in IST
				    Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				    // Last 7 days current week to 12:00 AM IST
				    StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				    StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				    // Last 7 days previous week to 12:00 AM IST
				    LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				    StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				    StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				    EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				    // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				      // Reference all dynamic parameters
				    IMCityParam = if Value.Is(IM_City_Parameter, type list) then IM_City_Parameter else {IM_City_Parameter},
				    RegionParam = if Value.Is(Region_Parameter, type list) then Region_Parameter else {Region_Parameter},
				    ZoneParam = if Value.Is(Zone_Parameter, type list) then Zone_Parameter else {Zone_Parameter},
				    StoreIDParam = if Value.Is(StoreID_Parameter, type list) then StoreID_Parameter else {StoreID_Parameter},
				    DeliveryTypeParam = if Value.Is(DeliveryType_Parameter, type list) then DeliveryType_Parameter else {DeliveryType_Parameter},
				    DeliverySlotParam = if Value.Is(DeliverySlot_Parameter, type list) then DeliverySlot_Parameter else {DeliverySlot_Parameter},
				
				    // BUild Dynamic Conditions
				    IMCityCondition = if List.NonNullCount(IMCityParam) > 0 then " | where city in (" & Text.Combine(List.Transform(IMCityParam, each "'" & _ & "'"), ", ") & ")" else "",
				    RegionCondition = if List.NonNullCount(RegionParam) > 0 then " | where region in (" & Text.Combine(List.Transform(RegionParam, each "'" & _ & "'"), ", ") & ")" else "",
				    ZoneCondition = if List.NonNullCount(ZoneParam) > 0 then " | where zone in (" & Text.Combine(List.Transform(ZoneParam, each "'" & _ & "'"), ", ") & ")" else "",
				    StoreIDCondition = if List.NonNullCount(StoreIDParam) > 0 then " | where store_id in (" & Text.Combine(List.Transform(StoreIDParam, each "'" & _ & "'"), ", ") & ")" else "",
				    DeliveryTypeCondition = if List.NonNullCount(DeliveryTypeParam) > 0 then " | where delivery_type in (" & Text.Combine(List.Transform(DeliveryTypeParam, each "'" & _ & "'"), ", ") & ")" else "",
				    DeliverySlotCondition = if List.NonNullCount(DeliverySlotParam) > 0 then " | where delivery_slot in (" & Text.Combine(List.Transform(DeliverySlotParam, each "'" & _ & "'"), ", ") & ")" else "",
				    
				    // Combine All Filters
				    CombinedFilters = IMCityCondition & RegionCondition & ZoneCondition & StoreIDCondition & DeliveryTypeCondition & DeliverySlotCondition,
				
				    // Format the query with dynamic start and end times
				    Query = "    let currentUser = current_principal_details()['UserPrincipalName'];
				    let userCities = toscalar(
				        Anobis_RLS_MV
				        | where UserEmail_ID == currentUser
				        | summarize make_list(city)
				    );
				    let hasAllAccess = toscalar(
				        Anobis_RLS_MV
				        | where UserEmail_ID == currentUser and city == 'cities'
				        | count
				    );
				    let today = " & TableName & " 
				        |where created_at_ist >= datetime('"& StartOfLast7DaysFormatted &"') 
				        |where created_at_ist <= datetime('"& EndofCurrentDateFormatted &"')
				        | where updated_at_ist <= datetime('"& EndofCurrentDateFormatted &"') 
				                and ((hasAllAccess > 0) or (city in (userCities)))
				                "& CombinedFilters &"
				        | where dp_order_type == 'INSTAMART'
				        | extend is_sdc = iff(cancel_type == 'CANCEL_TYPE_SWIGGY_DRIVEN_CANCELLATION', 1.0, 0.0)
				        | extend is_delivered = iff(status == 'COMPLETED', 1.0, 0.0)
				        | summarize 
				        SDCCount = sum(is_sdc),
				        DeliveredDistinctCount = dcount(iff(status == 'COMPLETED', order_id, ''))
				        by bin(created_at_ist, 1d)
				        | extend ['SDC%'] = round(iff(DeliveredDistinctCount == 0, 0.0, 100.0 * SDCCount / DeliveredDistinctCount),2),
				         Time_period = 'Daily Trend'
				        | project Time=created_at_ist, ['SDC%'], Time_period;
				        let last_week = " & TableName & " 
				        | where created_at_ist >= datetime('" & StartOfLastWeekFormatted & "')
				        | where created_at_ist <= datetime('"& EndofLastWeekFormatted &"') 
				        | where updated_at_ist <= datetime('"& EndofLastWeekFormatted &"')
				                and ((hasAllAccess > 0) or (city in (userCities)))
				                "& CombinedFilters &"
				        | where dp_order_type == 'INSTAMART'
				        | extend is_sdc = iff(cancel_type == 'CANCEL_TYPE_SWIGGY_DRIVEN_CANCELLATION', 1.0, 0.0)
				        | extend is_delivered = iff(status == 'COMPLETED', 1.0, 0.0)
				        | extend created_at_ist = datetime_add('hour', 168, created_at_ist)
				        | summarize 
				        SDCCount = sum(is_sdc),
				        DeliveredDistinctCount = dcount(iff(status == 'COMPLETED', order_id, ''))
				        by bin(created_at_ist, 1d)
				        | extend ['SDC%'] = round(iff(DeliveredDistinctCount == 0, 0.0, 100.0 * SDCCount / DeliveredDistinctCount),2),
				         Time_period = '1 Week Ago'
				        | project Time=created_at_ist, ['SDC%'], Time_period;
				        today
				        | union last_week",
				   
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster, DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				      #"Inserted Day of Week" = Table.AddColumn(Source, "Day of Week", each Date.DayOfWeek([Time]), Int64.Type),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Day of Week", "Week", each if [Day of Week] = 1 then "Mon" else if [Day of Week] = 2 then "Tue" else if [Day of Week] = 3 then "Wed" else if [Day of Week] = 4 then "Thur" else if [Day of Week] = 5 then "Fri" else if [Day of Week] = 6 then "Sat" else if [Day of Week] = 0 then "Sun" else null)
				in
				    #"Added Conditional Column"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

