table 'IM AOV Count Decomposition Tree- Yesterday'
	lineageTag: 69590a79-f011-485d-a3eb-8f5fe87e195e

	measure 'Measure 2'
		lineageTag: 56758ef3-d9b5-4386-8091-88877c326750

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column City
		dataType: string
		lineageTag: 97f58443-cb23-4201-bc98-688fe3b51d89
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fd80a909-6740-4e31-bad6-47ce55b05071
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 6ef3c81c-0575-455e-890b-1df39ffc7f3b
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: string
		lineageTag: 83032027-400b-4008-a1aa-b9162d80acdb
		summarizeBy: none
		sourceColumn: Store ID

		annotation SummarizationSetBy = Automatic

	column 'Delivery Type'
		dataType: string
		lineageTag: e5ae0b3d-2590-4351-8ee5-92c18dfb2a79
		summarizeBy: none
		sourceColumn: Delivery Type

		annotation SummarizationSetBy = Automatic

	column GroupGmv
		dataType: double
		lineageTag: aa77bf68-4b0f-420c-baec-486acfd912b6
		summarizeBy: sum
		sourceColumn: GroupGmv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GroupCounter
		dataType: int64
		formatString: 0
		lineageTag: fc1defe2-7631-4f06-b32a-f7d5a3b0e697
		summarizeBy: sum
		sourceColumn: GroupCounter

		annotation SummarizationSetBy = Automatic

	column 'Delivery Slot'
		dataType: string
		lineageTag: 61c45094-a572-48db-9522-246581f6f880
		summarizeBy: none
		sourceColumn: Delivery Slot

		annotation SummarizationSetBy = Automatic

	partition 'IM AOV Count Decomposition Tree- Yesterday' = m
		mode: import
		queryGroup: IM\IM-Yesterday\IM-Sales\IM_AOV
		source = ```
				let
				    // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get yesterday's date (in IST)
				    YesterdayDateTime = TodaysDateTime - #duration(1, 0, 0, 0),
				
				    // Set Start of Yesterday to 12:00 AM IST
				    StartOfYesterday = DateTime.FromText(Date.ToText(DateTime.Date(YesterdayDateTime)) & " 00:00:00"),
				
				    // Set End of Today to 00:00 AM IST
				    EndOfYesterday = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) & " 00:00:00"),
				
				    // Format the start and end dates to yyyy-MM-dd HH:mm:ss format
				    StartOfYesterdayFormatted = DateTime.ToText(StartOfYesterday, "yyyy-MM-dd HH:mm:ss"),
				    EndOfYesterdayFormatted = DateTime.ToText(EndOfYesterday, "yyyy-MM-dd HH:mm:ss"),
				
				    // // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // // Format the query with dynamic start and end times for yesterday in IST
				    Query = TableName & " 
				    | where created_at_ist >= datetime(' " & StartOfYesterdayFormatted & " ')
				    | where  created_at_ist < datetime('"& EndOfYesterdayFormatted &"') 
				    | extend counter = case(order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level), 1, 0) 
				    | where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED') 
				    | summarize GroupGmv = sum(gmv), GroupCounter = sum(counter) by city, region, zone, store_id, delivery_type, delivery_slot",
				    
				    Source = AzureDataExplorer.Contents(Cluster, DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"city", "City"}, {"region", "Region"}, {"zone", "Zone"}, {"store_id", "Store ID"}, {"delivery_type", "Delivery Type"}, {"delivery_slot", "Delivery Slot"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

