table 'IM Cancelled Decompotion Tree- Yesterday'
	lineageTag: c9b1c582-6cf8-4191-a611-71170ba9a69f

	column City
		dataType: string
		lineageTag: 35e4a276-a365-494d-a3f9-ce2e925f219e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 537f6839-56cd-4a24-9f35-aec5c8c0f0bb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 39c6ece4-1c35-49f9-8622-11308a05a565
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: string
		lineageTag: e6b458d5-b7ab-46a2-a97f-5da178260f22
		summarizeBy: none
		sourceColumn: Store ID

		annotation SummarizationSetBy = Automatic

	column 'Delivery Type'
		dataType: string
		lineageTag: 840a3024-9d61-4b1c-a2a8-21dfc3a5648e
		summarizeBy: none
		sourceColumn: Delivery Type

		annotation SummarizationSetBy = Automatic

	column count_
		dataType: int64
		formatString: 0
		lineageTag: 99001a48-dc54-4158-ab64-9ae9d7d6c8f9
		summarizeBy: sum
		sourceColumn: count_

		annotation SummarizationSetBy = Automatic

	column 'Delivery Slot'
		dataType: string
		lineageTag: 22512eab-ce59-4640-93f8-119035649537
		summarizeBy: none
		sourceColumn: Delivery Slot

		annotation SummarizationSetBy = Automatic

	partition 'IM Cancelled Decompotion Tree- Yesterday' = m
		mode: import
		queryGroup: 'IM\IM-Yesterday\IM-Cancellation\IM-Cancelled Orders'
		source = ```
				let
				    // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get yesterday's date (in IST)
				    YesterdayDateTime = TodaysDateTime - #duration(1, 0, 0, 0),
				    // Set Start of Yesterday to 12:00 AM IST
				    StartOfYesterday = DateTime.FromText(Date.ToText(DateTime.Date(YesterdayDateTime)) & " 00:00:00"),
				    // Set End of Today to 00:00 AM IST
				    EndOfYesterday = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) & " 00:00:00"),
				    // Format the start and end dates to yyyy-MM-dd HH:mm:ss format
				    StartOfYesterdayFormatted = DateTime.ToText(StartOfYesterday, "yyyy-MM-dd HH:mm:ss"),
				    EndOfYesterdayFormatted = DateTime.ToText(EndOfYesterday, "yyyy-MM-dd HH:mm:ss"),
				
				    // // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // // Format the query with dynamic start and end times for yesterday in IST
				    Query = TableName & " 
				    | where created_at_ist >= datetime(' " & StartOfYesterdayFormatted & " ')
				    | where  created_at_ist < datetime(' " & EndOfYesterdayFormatted & " ')
				    | where dp_order_type == 'INSTAMART' and status == 'CANCELLED' and (order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level))
				    | summarize count() by city, region, zone, store_id, delivery_type, delivery_slot",
				
				    Source = AzureDataExplorer.Contents(Cluster, DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"city", "City"}, {"region", "Region"}, {"zone", "Zone"}, {"store_id", "Store ID"}, {"delivery_type", "Delivery Type"}, {"delivery_slot", "Delivery Slot"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

