table 'IM Cancelled Decompotion Tree- Last 4 Weeks'
	lineageTag: 8d651084-7a48-4554-aaf8-d74dc6f68db1

	column City
		dataType: string
		lineageTag: 5f2228e4-45ea-4fac-99e6-4170c877540c
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 102f954a-4709-4e0d-9246-95ae6f0bc5e0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: b40554f4-9f8f-46ef-8d17-c0bbef9f9b82
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: string
		lineageTag: 5754dfa1-84d6-460e-b9da-58ef25af2aeb
		summarizeBy: none
		sourceColumn: Store ID

		annotation SummarizationSetBy = Automatic

	column 'Delivery Type'
		dataType: string
		lineageTag: cb0dc845-731c-48a2-8b47-3a8c9604e18d
		summarizeBy: none
		sourceColumn: Delivery Type

		annotation SummarizationSetBy = Automatic

	column count_
		dataType: int64
		formatString: 0
		lineageTag: 49a60bf5-a11b-4dac-bfa6-4770ae58affa
		summarizeBy: sum
		sourceColumn: count_

		annotation SummarizationSetBy = Automatic

	column 'Delivery Slot'
		dataType: string
		lineageTag: a5044d7d-507e-42a3-a9bc-2a077a1eaea3
		summarizeBy: none
		sourceColumn: Delivery Slot

		annotation SummarizationSetBy = Automatic

	partition 'IM Cancelled Decompotion Tree- Last 4 Weeks' = m
		mode: import
		queryGroup: 'IM\IM-Last 4 Weeks\IM-Cancellation\IM-Cancelled Orders'
		source = ```
				let
				 // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 7 days ago in IST
				    Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				    // Set the start of the last 7 days to 12:00 AM IST
				    StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				    StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    EndofLast7Days = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofLast7DayFormatted = DateTime.ToText(EndofLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // Format the query with dynamic start and end times
				    Query = TableName & " 
				    | where created_at_ist >= datetime('" & StartOfLast7DaysFormatted & "')
				    | where  created_at_ist < datetime(' " & EndofLast7DayFormatted & " ')
				    | where dp_order_type == 'INSTAMART' and status == 'CANCELLED' and (order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level))
				    | summarize count() by city, region, zone, store_id, delivery_slot, delivery_type",
				
				    Source = AzureDataExplorer.Contents(Cluster, DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"city", "City"}, {"region", "Region"}, {"zone", "Zone"}, {"store_id", "Store ID"}, {"delivery_type", "Delivery Type"}, {"delivery_slot", "Delivery Slot"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

